<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Warehouse;

class WarehouseSeeder extends Seeder
{
    public function run()
    {
        $warehouses = [
            [
                'name' => 'Colombo Central Hub',
                'location' => 'Colombo',
                'address' => '123 Galle Road, Colombo 03',
                'contact_number' => '011-2345678',
                'email' => 'colombo.hub@warehouse.com',
                'alternate_contact' => '011-2345679',
                'manager_name' => 'Rajitha Perera',
                'opening_time' => '07:00:00',
                'closing_time' => '22:00:00',
                'pickup_available' => true,
                'storage_capacity' => 5000,
                'current_occupancy' => 3200,
                'is_active' => true,
                'status' => 'operational',
                'has_security' => true,
                'has_cctv' => true,
                'has_loading_dock' => true,
                'has_parking' => true,
                'has_climate_control' => true,
                'has_refrigeration' => true,
                'has_hazmat_storage' => true,
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'open_24_7' => false,
                'open_on_holidays' => true,
                'latitude' => 6.9271,
                'longitude' => 79.8612,
                'city' => 'Colombo',
                'state' => 'Western Province',
                'country' => 'Sri Lanka',
                'postal_code' => '00300',
                'special_instructions' => 'Access from Galle Road entrance. Security clearance required for vehicles.',
                'delivery_instructions' => 'Loading bay available 24/7. Prior appointment needed for bulk deliveries.',
                'available_services' => json_encode([
                    'Cross-docking',
                    'Inventory management',
                    'Order fulfillment',
                    'Climate controlled storage',
                    'Hazmat storage',
                    'Container handling'
                ]),
                'restricted_items' => json_encode([
                    'Unregistered chemicals',
                    'Explosives',
                    'Unauthorized biological materials'
                ]),
                'storage_rate_daily' => 1500.00,
                'storage_rate_monthly' => 35000.00,
                'handling_fee' => 250.00,
                'currency' => 'LKR',
                'is_insured' => true,
                'insurance_expiry' => '2025-12-31',
                'license_number' => 'WH-COL-2024-001',
                'license_expiry' => '2025-12-31',
                'last_inspection_at' => '2024-01-15',
                'next_maintenance_at' => '2024-06-15'
            ],
            [
                'name' => 'Kandy Distribution Center',
                'location' => 'Kandy',
                'address' => '456 Peradeniya Road, Kandy',
                'contact_number' => '081-2234567',
                'email' => 'kandy.dc@warehouse.com',
                'alternate_contact' => '081-2234568',
                'manager_name' => 'Kumari Silva',
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'pickup_available' => true,
                'storage_capacity' => 3500,
                'current_occupancy' => 2100,
                'is_active' => true,
                'status' => 'operational',
                'has_security' => true,
                'has_cctv' => true,
                'has_loading_dock' => true,
                'has_parking' => true,
                'has_climate_control' => true,
                'has_refrigeration' => false,
                'has_hazmat_storage' => false,
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'open_24_7' => false,
                'open_on_holidays' => false,
                'latitude' => 7.2906,
                'longitude' => 80.6337,
                'city' => 'Kandy',
                'state' => 'Central Province',
                'country' => 'Sri Lanka',
                'postal_code' => '20000',
                'special_instructions' => 'Hill country location. Heavy vehicles require special permits.',
                'delivery_instructions' => 'Early morning deliveries preferred. Limited access during peak hours.',
                'available_services' => json_encode([
                    'Warehouse storage',
                    'Distribution services',
                    'Order processing',
                    'Climate controlled storage',
                    'Local delivery'
                ]),
                'restricted_items' => json_encode([
                    'Hazardous materials',
                    'Perishable goods without proper packaging'
                ]),
                'storage_rate_daily' => 1200.00,
                'storage_rate_monthly' => 28000.00,
                'handling_fee' => 200.00,
                'currency' => 'LKR',
                'is_insured' => true,
                'insurance_expiry' => '2025-12-31',
                'license_number' => 'WH-KAN-2024-001',
                'license_expiry' => '2025-12-31',
                'last_inspection_at' => '2024-01-10',
                'next_maintenance_at' => '2024-07-10'
            ],
            [
                'name' => 'Galle Maritime Hub',
                'location' => 'Galle',
                'address' => '789 Port Road, Galle Fort',
                'contact_number' => '091-2234567',
                'email' => 'galle.hub@warehouse.com',
                'alternate_contact' => '091-2234568',
                'manager_name' => 'Mohamed Fazil',
                'opening_time' => '05:00:00',
                'closing_time' => '21:00:00',
                'pickup_available' => true,
                'storage_capacity' => 4000,
                'current_occupancy' => 2800,
                'is_active' => true,
                'status' => 'operational',
                'has_security' => true,
                'has_cctv' => true,
                'has_loading_dock' => true,
                'has_parking' => true,
                'has_climate_control' => true,
                'has_refrigeration' => true,
                'has_hazmat_storage' => false,
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
                'open_24_7' => false,
                'open_on_holidays' => true,
                'latitude' => 6.0535,
                'longitude' => 80.2210,
                'city' => 'Galle',
                'state' => 'Southern Province',
                'country' => 'Sri Lanka',
                'postal_code' => '80000',
                'special_instructions' => 'Located within UNESCO World Heritage site. Heritage building guidelines apply.',
                'delivery_instructions' => 'Port access available. Customs clearance facility on-site.',
                'available_services' => json_encode([
                    'Port storage',
                    'Customs clearance',
                    'Cold storage',
                    'Container handling',
                    'Export packaging',
                    'Maritime logistics'
                ]),
                'restricted_items' => json_encode([
                    'Non-declared imports',
                    'Restricted marine items'
                ]),
                'storage_rate_daily' => 1300.00,
                'storage_rate_monthly' => 30000.00,
                'handling_fee' => 225.00,
                'currency' => 'LKR',
                'is_insured' => true,
                'insurance_expiry' => '2025-12-31',
                'license_number' => 'WH-GAL-2024-001',
                'license_expiry' => '2025-12-31',
                'last_inspection_at' => '2024-01-20',
                'next_maintenance_at' => '2024-07-20'
            ],
            [
                'name' => 'Jaffna Central Facility',
                'location' => 'Jaffna',
                'address' => '45 Hospital Road, Jaffna',
                'contact_number' => '021-2234567',
                'email' => 'jaffna.hub@warehouse.com',
                'alternate_contact' => '021-2234568',
                'manager_name' => 'Thiyagarajah Kumar',
                'opening_time' => '07:00:00',
                'closing_time' => '21:00:00',
                'pickup_available' => true,
                'storage_capacity' => 2500,
                'current_occupancy' => 1500,
                'is_active' => true,
                'status' => 'operational',
                'has_security' => true,
                'has_cctv' => true,
                'has_loading_dock' => true,
                'has_parking' => true,
                'has_climate_control' => true,
                'has_refrigeration' => true,
                'has_hazmat_storage' => false,
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'open_24_7' => false,
                'open_on_holidays' => false,
                'latitude' => 9.6615,
                'longitude' => 80.0255,
                'city' => 'Jaffna',
                'state' => 'Northern Province',
                'country' => 'Sri Lanka',
                'postal_code' => '40000',
                'special_instructions' => 'Located near Jaffna Teaching Hospital. Special permits required for large vehicles.',
                'delivery_instructions' => 'Early morning deliveries preferred. Security check required.',
                'available_services' => json_encode([
                    'Storage',
                    'Distribution',
                    'Cold storage',
                    'Local delivery',
                    'Cross-docking'
                ]),
                'restricted_items' => json_encode([
                    'Hazardous materials',
                    'Unauthorized imports'
                ]),
                'storage_rate_daily' => 1000.00,
                'storage_rate_monthly' => 25000.00,
                'handling_fee' => 200.00,
                'currency' => 'LKR',
                'is_insured' => true,
                'insurance_expiry' => '2025-12-31',
                'license_number' => 'WH-JAF-2024-001',
                'license_expiry' => '2025-12-31',
                'last_inspection_at' => '2024-01-05',
                'next_maintenance_at' => '2024-07-05'
            ],
            [
                'name' => 'Batticaloa East Coast Hub',
                'location' => 'Batticaloa',
                'address' => '78 Trinco Road, Batticaloa',
                'contact_number' => '065-2234567',
                'email' => 'batti.hub@warehouse.com',
                'alternate_contact' => '065-2234568',
                'manager_name' => 'Abdul Majeed',
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'pickup_available' => true,
                'storage_capacity' => 3000,
                'current_occupancy' => 1800,
                'is_active' => true,
                'status' => 'operational',
                'has_security' => true,
                'has_cctv' => true,
                'has_loading_dock' => true,
                'has_parking' => true,
                'has_climate_control' => true,
                'has_refrigeration' => true,
                'has_hazmat_storage' => false,
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'open_24_7' => false,
                'open_on_holidays' => true,
                'latitude' => 7.7170,
                'longitude' => 81.7000,
                'city' => 'Batticaloa',
                'state' => 'Eastern Province',
                'country' => 'Sri Lanka',
                'postal_code' => '30000',
                'special_instructions' => 'Coastal facility with easy access to Batticaloa-Trincomalee highway.',
                'delivery_instructions' => 'Seafood storage available. Temperature controlled units.',
                'available_services' => json_encode([
                    'Cold storage',
                    'Seafood storage',
                    'Distribution',
                    'Local delivery',
                    'Cross-docking'
                ]),
                'restricted_items' => json_encode([
                    'Non-certified seafood',
                    'Hazardous materials'
                ]),
                'storage_rate_daily' => 1100.00,
                'storage_rate_monthly' => 26000.00,
                'handling_fee' => 200.00,
                'currency' => 'LKR',
                'is_insured' => true,
                'insurance_expiry' => '2025-12-31',
                'license_number' => 'WH-BAT-2024-001',
                'license_expiry' => '2025-12-31',
                'last_inspection_at' => '2024-01-08',
                'next_maintenance_at' => '2024-07-08'
            ],
            [
                'name' => 'Trincomalee Port Warehouse',
                'location' => 'Trincomalee',
                'address' => '234 Harbor Road, Trincomalee',
                'contact_number' => '026-2234567',
                'email' => 'trinco.port@warehouse.com',
                'alternate_contact' => '026-2234568',
                'manager_name' => 'Senthil Rajan',
                'opening_time' => '05:00:00',
                'closing_time' => '23:00:00',
                'pickup_available' => true,
                'storage_capacity' => 4500,
                'current_occupancy' => 3000,
                'is_active' => true,
                'status' => 'operational',
                'has_security' => true,
                'has_cctv' => true,
                'has_loading_dock' => true,
                'has_parking' => true,
                'has_climate_control' => true,
                'has_refrigeration' => true,
                'has_hazmat_storage' => true,
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']),
                'open_24_7' => false,
                'open_on_holidays' => true,
                'latitude' => 8.5874,
                'longitude' => 81.2152,
                'city' => 'Trincomalee',
                'state' => 'Eastern Province',
                'country' => 'Sri Lanka',
                'postal_code' => '31000',
                'special_instructions' => 'Deep water port access. Naval security clearance required.',
                'delivery_instructions' => 'Port authority clearance needed for bulk shipments.',
                'available_services' => json_encode([
                    'Port storage',
                    'Container handling',
                    'Customs clearance',
                    'Cold storage',
                    'Bulk cargo',
                    'Maritime logistics'
                ]),
                'restricted_items' => json_encode([
                    'Unauthorized maritime cargo',
                    'Non-declared imports'
                ]),
                'storage_rate_daily' => 1400.00,
                'storage_rate_monthly' => 32000.00,
                'handling_fee' => 250.00,
                'currency' => 'LKR',
                'is_insured' => true,
                'insurance_expiry' => '2025-12-31',
                'license_number' => 'WH-TRI-2024-001',
                'license_expiry' => '2025-12-31',
                'last_inspection_at' => '2024-01-12',
                'next_maintenance_at' => '2024-07-12'
            ],
            [
                'name' => 'Anuradhapura Heritage Logistics',
                'location' => 'Anuradhapura',
                'address' => '67 New Town Road, Anuradhapura',
                'contact_number' => '025-2234567',
                'email' => 'anuradhapura.hub@warehouse.com',
                'alternate_contact' => '025-2234568',
                'manager_name' => 'Bandara Dissanayake',
                'opening_time' => '06:00:00',
                'closing_time' => '20:00:00',
                'pickup_available' => true,
                'storage_capacity' => 3000,
                'current_occupancy' => 1700,
                'is_active' => true,
                'status' => 'operational',
                'has_security' => true,
                'has_cctv' => true,
                'has_loading_dock' => true,
                'has_parking' => true,
                'has_climate_control' => true,
                'has_refrigeration' => false,
                'has_hazmat_storage' => false,
                'operating_days' => json_encode(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
                'open_24_7' => false,
                'open_on_holidays' => false,
                'latitude' => 8.3114,
                'longitude' => 80.4037,
                'city' => 'Anuradhapura',
                'state' => 'North Central Province',
                'country' => 'Sri Lanka',
                'postal_code' => '50000',
                'special_instructions' => 'Located in new town area. Agricultural goods priority.',
                'delivery_instructions' => 'Early morning deliveries preferred for agricultural products.',
                'available_services' => json_encode([
                    'Agricultural storage',
                    'Distribution',
                    'Local delivery',
                    'Cross-docking',
                    'Packaging'
                ]),
                'restricted_items' => json_encode([
                    'Hazardous materials',
                    'Non-agricultural chemicals'
                ]),
                'storage_rate_daily' => 1000.00,
                'storage_rate_monthly' => 24000.00,
                'handling_fee' => 180.00,
                'currency' => 'LKR',
                'is_insured' => true,
                'insurance_expiry' => '2025-12-31',
                'license_number' => 'WH-ANU-2024-001',
                'license_expiry' => '2025-12-31',
                'last_inspection_at' => '2024-01-18',
                'next_maintenance_at' => '2024-07-18'
            ]
        ];

        foreach ($warehouses as $warehouse) {
            Warehouse::create($warehouse);
        }
    }
}
